// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplicationMetroNSK.Data;

#nullable disable

namespace MyApplicationMetroNSK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MyApplicationMetroNSK.Data.Models.DataForCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusTNP")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoefficientEvening")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoefficientNight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LengthOfService")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfessionalFees")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qualification")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegionalCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TariffRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataForCalculation");
                });

            modelBuilder.Entity("MyApplicationMetroNSK.Data.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EveningPayment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HolidayPayment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyPayment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongServicePay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightPayment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentForGapInShift")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentForQualification")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentForTheRegionalCoefficient")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PremiumPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfessionalFees")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TNPpremiymPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("MyApplicationMetroNSK.Data.Models.TimeCard", b =>
                {
                    b.Property<string>("NumberTimeCard")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayofWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("NumberTimeCard", "WorkType", "DayofWeek");

                    b.ToTable("TimeCards");
                });

            modelBuilder.Entity("MyApplicationMetroNSK.Data.Models.WorkedTimeCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EveningHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HolidayHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NightHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberTimeCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShiftGap")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WorkHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkedTimeCards");
                });
#pragma warning restore 612, 618
        }
    }
}
